### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Naomi-Mifsud** [moodleuulm/moodle-block_course_overview_campus#17]
Hi,

Please note that for academic year 2016/17 we have started making use of the 'Course Overview on Campus' block due to some changes in the infrastructure of the VLE. In previous years we have always used the 'Course Overview' block.

Since we launched this year's VLE, we have been receiving emails, mostly from tutors, with suggestions for the 'Course Overview on Campus' block. Below we identify the three most common suggestions we've been getting:
1. Courses should be displayed in chronological order, rather than in alphabetical order.
   For instance, we organise courses in Categories, namely, 'Academic Year 2016/17', 'Academic Year 2015/16', etc, and we have organised the categories so that 'Academic Year 2016/17' is displayed as the first option from the 'Category' filter menu in the 'Course Overview on Campus' block. When users use the 'All' option they prefer to see all courses for the current academic year listed first, followed by last year's courses, etc. At the moment, the courses are being displayed in alphabetical order.
   We are aware of the 'Filter by Term' option, however, in our case this is not a feasible option.
2. Choose a particular category to set default.
   By default, the 'Course Overview on Campus' block displays 'All' courses which the user is registered for. Is it possible to have a setting for the block where admin personnel can choose to set a particular category as default, please?
3. Allow users to rearrange the sequence in which the various courses for a particular category are displayed.
   This feature is available in the 'Course Overview' block, and therefore some of our users have been used to this feature in previous years.

Much thanks in advance.

Best Regards,
Naomi

**Comment by abias** [comment]
Hi Naomi-Mifsud,

thanks for your feedback to our block. I really appreciate it.
Currently, we are quite busy working on some big projects, but I will try to come back to you with a real feedback as soon as possible.

In the meantime, you might want to tell me if you have developers who could implement the improvements or not.

Thanks for your patience,
Alex

**Comment by Naomi-Mifsud** [comment]
Dear Alex,

Thank you for your prompt attention.

Unfortunately, we currently don't have developers who can help with the implementations.

We look forward to future developments.

Much thanks and Kind regards,
Naomi

**Comment by abias** [comment]
Hi Naomi,

there requests have been untouched for more than a year now and I am sorry for that.

I would like to give you a final feedback about them:

> Courses should be displayed in chronological order, rather than in alphabetical order.
> For instance, we organise courses in Categories, namely, 'Academic Year 2016/17', 'Academic Year 2015/16', etc, and we have organised the categories so that 'Academic Year 2016/17' is displayed as the first option from the 'Category' filter menu in the 'Course Overview on Campus' block. When users use the 'All' option they prefer to see all courses for the current academic year listed first, followed by last year's courses, etc. At the moment, the courses are being displayed in alphabetical order.
> We are aware of the 'Filter by Term' option, however, in our case this is not a feasible option.
> Choose a particular category to set default.

I understand this request, but I don't know what I could do about it with reasonable effort. Currently, all displayed courses are ordered alphabetically. This is an understandable and scannable sorting for all users. Sorting courses in chronological order has to be defined: Do you mean sorting by course start date? By the academic year of its parent category? By enrolment start date? I am afraid that we would end up with a new bunch of setting for sorting and probably also user settings for sorting. This is clearly out of scope for us because of limited resources. That's why I would finally deny this request.

> By default, the 'Course Overview on Campus' block displays 'All' courses which the user is registered for. Is it possible to have a setting for the block where admin personnel can choose to set a particular category as default, please?

I understand this request, too. I also think that it could be implemented in reasonable time. However, 
again due to limited resources, I cannot spend the time for this feature now and in the near future. Sorry.

> Allow users to rearrange the sequence in which the various courses for a particular category are displayed.
> This feature is available in the 'Course Overview' block, and therefore some of our users have been used to this feature in previous years.

Rearranging the course list is on the list of disregarded features (see https://github.com/moodleuulm/moodle-block_course_overview_campus/blob/master/README.md#disregarded-moodle-features). We don't have any plan and motivation to introduce this because we think this would conflict with the filtering / hiding feature and confuse users.

Thanks for your patience and understanding,
Alex

**Comment by Naomi-Mifsud** [comment]
Hi Alex,

Thank you for your reply and the detailed information.

We understand your point of view. As we have continued using it most users have got accustomed to this plugin's features and are very satisfied.

Thanks,
Naomi
