### ISSUE TITLE
"Undefined variable: modchoices" error whenever I perform an upgrade

### ISSUE THREAD

**Issue by NMCPaul** [moodleuulm/moodle-block_course_overview_campus#21]
I'm running Moodle 3.3+ with PHP 7.0 and the latest version of the block code (master branch).  Every time I perform a command-line upgrade, I receive the following error:

`PHP Notice:  Undefined variable: modchoices in [MOODLEROOT]/blocks/course_overview_campus/settings.php on line 95`

This happens for every upgrade, even if it doesn't involve this plugin directly.  Any thoughts on what I might do to fix it?

**Comment by abias** [comment]
Hi Paul,

thanks for your bug report.

Please note that this plugin is not yet officially tested with Moodle 3.3 and due to the changes on the Dashboard in 3.3 I expect that there may be some problems with the plugin's course news feature.

I had a look at the debug notice and while I couldn't find any problem on line 95, I added a small patch (commit 0b4fab854addceaa4e8a4f92208777363bd55a5d) to hopefully overcome this plugin.

Please give it a try and report back to me if it solves your problem or not.

Thanks,
Alex

**Comment by NMCPaul** [comment]
Alex,

That appears to have done the trick, thanks.  Also - the reason it was on line 95 is because somehow this one plugin wasn't being flagged as in need of an upgrade, despite it clearly needing one.

Either way, thanks for looking into this.

Paul
