### ISSUE TITLE
Suggestion: Separate link for category/top category at course list output

### ISSUE THREAD

**Issue by bozicm** [moodleuulm/moodle-block_course_overview_campus#29]
Hi, I support a Moodle setup that is being used in sort of multisite setup by using top categories as "site" per organization. Unfortunately Moodle itself doesn't have a really useful way of filtering the categories by "site".

Your plugin is almost there for out needs, but currently the course link covers both course and category name.

Having a separate link for category at course list would help the users very much at browsing their all available courses and organization's categories. Would it be possible for you to make such a change? Or would you rather have a pull request?

**Comment by abias** [comment]
Hi Martin,

thank you for your suggestion.

Currently, each course list entry - including the information in the second line below the course title - links as a whole to the course main page. This was done because we did want to have a large clickable area and didn't want to link to anything else but the course main page.

However, I think it would be a no-brainer to add another checkbox setting "block_course_overview_campus | secondrowseparatelinks" to /admin/settings.php?section=block_course_overview_campus_courseoverviewlist which will, if enabled, output sepate links to all of the details which are shown in the second line:
* Course short name would also link to the course main page
* Course term name would probably haven't any link
* Course parent category name would link to the parent category
* Course top level category name would link to the top level category
* Course teacher names would link to each teacher's personal profile page (if the user is allowed to view profile pages)

Unfortunately, we don't have any resources for this implementation currently. But don't hesitate to submit a well-shaped pull request :)

Cheers,
Alex

**Comment by abias** [comment]
Hi, 

this issue has been stale for nearly a year now. 

While we still support the spirit of this issue, it won't be done anymore as we are foreseeably transitioning our own usage of this block to the Dashboard blocks which have been dramatically improved from Moodle 3.6 on and thus can't spend any more substantial resources on this plugin.

Cheers,
Alex
